version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map host port (from .env APP_PORT or default 3000) to container port 3000
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - bgutil-provider
    volumes:
      # Persist downloaded files by mapping host ./downloads to container /usr/src/app/downloads
      - ./downloads:/usr/src/app/downloads
      # Persist .config directory (e.g., for cookies at .config/yt-dlp/cookies.txt)
      - ./.config:/usr/src/app/.config
    environment:
      - NODE_ENV=production
      - PORT=3000 # Port your Node.js app listens on inside the container
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped
    env_file:
      - .env # Loads environment variables from a .env file in your project root

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: bgutil-provider
    ports:
      - "4416:4416"
    restart: unless-stopped