version: '3.8'

services:
  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: bgutil-provider
    ports:
      - "4416:4416"
    restart: unless-stopped
    networks:
      - video-episode-downloader-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4416', (res) => process.exit(0)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Main video episode downloader application
  video-episode-downloader:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: video_episode_downloader
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - video-episode-downloader-data:/app/data
    depends_on:
      bgutil-provider:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - video-episode-downloader-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  video-episode-downloader-data:
networks:
  video-episode-downloader-network:
    driver: bridge
    name: video-episode-downloader-network
